version: "3.8"
services:
  rasa:
    build:
      context: .
      dockerfile: docker/core/Dockerfile_local
    image: sivasirius/utcourt-rasa-core:latest
    container_name: rasa
    ports:
      - 5005:5005
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    env_file:
      - .env
  actions:
    build:
      context: .
      dockerfile: docker/actions/Dockerfile_local
    image: sivasirius/utcourt-rasa-actions:latest
    container_name: actions
    expose: ["5055"]
    env_file:
      - .env
